### ISSUE TITLE
More 101 problems

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#100]
[f=0010498] Error: LuaRules::RunCallIn: error = 2, Update, [Internal Lua error: Call failure] [string "lups/ParticleClasses/airjet.lua"]:371: bad argument #4 to 'IsPosInAirLos' (Invalid allyTeam)

Gets spammed a billion times when things shoot.

Tanks show up black, don't know why. Not all of them and not all the time. Some sort of shader issue.

There is no "Banker" spambot difficulty, only Regular, Athlete and Diabolic.

**Comment by FLOZi** [comment]
All of these are now resolved
