### ISSUE TITLE
New Overlord model animations

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#106]
So new Overlord is different than Union. It has more legs and different weapon configs. Here's what's what:

Initialization anims:

Doors are default open, need to rotate 80 on x-axis to closed position.
Gears (and joints & doors) 1-7 need to be rotated along y-axis, in this order:

1: -45
2: -90
3: -135
4: 180
5: 135
6: 90
7: 45

turret_1 is fine but mantlet_1 needs to be moved forward along z-axis to poke out. Try about 40.

turret_2 needs to be rotated -45, turret_4 rotated 135

turret_2 has barrel_2 and barrel_3, turret 4 has barrel_4 and barrel_5

missile_doors work the same as Union

each laser_emitter has 4 weapons corresponding with the ID+4. For example laser_emitter_6 has flares for weapon 6, 7, 8 and 9. emitter_6 is fine; emitter_10 needs to be rotated 90 degrees, emitter_14 180 degrees and emitter_18 -90 degrees.

Landing anims:

Rotate gear#_joints to -90 along x axis and gear#s to 110 along x axis to land. gear#_door 

main_door is attached to door_struts which have to move forward on z-axis while door is swinging open by maybe 40.

starting from flare_24 there are groups of 4 lasers around a little hub with emitters on the top bottom right and left. so each will need the direction the hub is facing, and up/down right/left for their firing arcs. 

That should be about it. It has 41 weapons in total, including a Sniper artillery cannon, 4 LRM-20s, 16 LBLs, 16 MPLs, and 4 AC/10s.

**Comment by FLOZi** [comment]
Done all I can do unless weapon limit is increased or we remove some weapons (inc renaming model flare pieces)
