### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#116]
Since we can tweak accuracy dynamically why not? 

1) Make everything less accurate at long range, ie 50% range, though technically we could look at actual Battletech weapon stats since they all have range accuracy profiles (divided into short, medium and long range with accuracy modifiers at each) and base it on that to be as anal as possible.
2) Make targetingcomputer  customparam that makes most non-missile weapons more accurate, or just negates long range inaccuracy. Exceptions would be Ultra and Rotary ACs, which would be a good way to balance them.
3) Make c3  customparam. Mechs with c3 can share targeting data and negate long-range inaccuracy if another mech with c3 is in short range of a target. IE have a brawler with c3 up close to the enemy and a sniper far back that then doesn't suffer accuracy loss.
4) ECM would negate c3 effect, either based on target or based on if the closer c3 is within enemy ECM (latter preferred).
5) Stealth armor: Anything firing at a unit with Stealth armor gets big accuracy nerf.

**Comment by FLOZi** [comment]
I think this is all possible, code wise. How to communicate any of it to the player?

**Comment by zverofaust** [comment]
We could use graphics to highlight enemy targets that are being "c3'd", ie, friendly Mechs will have bonuses firing against. Fuck it's complicated though. Like C3 should rely on a Master and a Slave with Slaves sharing targeting data given by Masters. The main reason I want to do this is that C3 units in Mechs take up space and weight and are part of the overall balancing of each design. Every C3 Mech we have whose C3 is useless is by design inferior because it can't make use of it.
