### ISSUE TITLE
More UVMapping woes:

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#118]
- [ ] Brutus
- [ ] Goblin Transport
- [ ] Goblin IFV
- [ ] Mamono
- [ ] Alacorn
- [ ] DI Morgan
- [ ] Typhoon
- [ ] Pilum (and Arrow IV version)
- [ ] Sturmfeur
- [ ] Prowler
- [ ] Gurteltier
- [ ] Ferret (VTOL)
- [ ] Cyrano (VTOL)

**Comment by FLOZi** [comment]
Combined into #92
