### ISSUE TITLE
Removal of 'legacy' TA unit panel & expanding Unit Card

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#12]
Legacy TA control panel needs to be removed and replaced by buttons and functions of the Unit Card.

See this Wiki page: https://github.com/SpringMCLegacy/SpringMCLegacy/wiki/Dev:-Unit-Card-Additions

**Comment by FLOZi** [comment]
Isn't Anarchids build menu widget already included? (even if unfinished)

**Comment by gajop** [comment]
Not sure if this is the right issue, but I'd like to open the issue of how Mechs are categorized into roles: https://github.com/SpringMCLegacy/SpringMCLegacy/wiki/Gameplay#roles .
I think this is fairly incorrect (useless) as it combines tonnage, weapon range and type, and special abilities into a single "role" categorization system.
I would much rather prefer to see mechs differentiated by tonnage and weapon range (short, medium and long), while other info such as ewar, speed, weapon types, armor and so on available as details.

Weapons should definitely have icons that makes it easy to differentiate between type (lasers/pcc, AC/projectiles and missiles) and range (short, medium and long). I think Mechcommander 1 did a good job by using colors for range and icons for types.

Thoughts?
