### ISSUE TITLE
Stealth Armour

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#123]
Stealth armor:

- Is On/Off-able

When on:

Is totally invisible to any non-visual detection except Siesmic;
Generates a lot of heat, enough that it can't be perma on;
Is immune to lock-on missiles (unless TAG'd/Narc'd), but also can not use its own lock-on missiles (unless at a TAG/Narc) (the BT rule is that Mechs with active Stealth Armour act like they're being hit with enemy ECM);

When off:

Becomes normal, but has an ECM.

Stealth could potentially be a 3rd selection for Radar On/Off, so there would be On, Off, Stealth. Or is own button. IDK.

**Comment by FLOZi** [comment]
Gonna reopen this one as Stealth Armour is still part of the proposed revised game design and is still completely absent currently.
