### ISSUE TITLE
Destroyed component icon doesn't disappear when Mech is repaired

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#125]
The destroyed component icon (little explosion) that appears when a Mech loses an appendage doesn't disappear if the Mech gets repaired.

**Comment by FLOZi** [comment]
Tested this with an fs_urby, losing an arm to LRMs. Couldn't replicate. i.e. the icon was removed after mechbay repair.

**Comment by FLOZi** [comment]
Had it happen when I had an avatar lose a lunch of limbs so will try and replicate it that way.

**Comment by zverofaust** [comment]
For me it happened with a Dervish.
