### ISSUE TITLE
Mechs target dropships across map.

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#127]
As title.

**Comment by FLOZi** [comment]
If 50c2a79 is not sufficient, all weapons already have dropship in their badtargetcategory and dropship have their 'power' set to 1. So the only remaining avenue is intervening with TargetWeight lus callin or https://springrts.com/wiki/Lua:Callins#AllowWeaponTarget lua gadget callin.

**Comment by zverofaust** [comment]
I think it's necessary. Mechs won't ignore nearer targets but they'll still "stare at" an enemy dropship meaning they arent looking where I want them looking.

Would it be possible to also/instead make dropships untargetable when they're blasting off/entering the atmosphere? IMHO they only should be shot at once they enter the "hover" stage of their landing or the immediate takeoff stage.

**Comment by FLOZi** [comment]
In my testing mechs were pretty strongly avoiding dropships unless that was the only thing targetable. :(

re: untargetable when blasting off etc yes possible but by the exact same lua methods.

**Comment by zverofaust** [comment]
Thats the issue, unless they're the only thing targetable, most of the time there isn't anything else targetable because nothing is in range or visible but dropships always are. Sometimes you want a Mech to 'watch' a specific direction for enemies but instead they turn and admire a dropship.

**Comment by FLOZi** [comment]
Sufficiently addressed to close.
