### ISSUE TITLE
"Dropship Arrived" bug

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#129]
Several people reported random issue with a Dropship not dropping off its order and leaving, and "Dropship Arrived" state remaining indefinitely, preventing further orders. 

No idea what's causing. Beacons weren't under attack etc.

**Comment by FLOZi** [comment]
Did they get the 'buggin out' message when this happened? Demos would be really useful for tracking down how to replicate dropship bugs.

**Comment by FLOZi** [comment]
Feel optimistic that this is now resolved.
