### ISSUE TITLE
Sector LOS, Radar and BAP issue

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#130]
This is complicated so I'll do my best.

**SCENARIO 1**

See image: 

https://i.imgur.com/zbGqb5G.png

On the right is a Jagermech sitting with its radar on and weapons off.
On the left is an Enfield medium and a Raven that are hostile to it (on the same team). Currently, both have their radars OFF, but the Enfield's radar will not detect the Jager while the Raven's will.

The following behaviour has been observed:

- [x] A) If the Enfield turns its radar ON, the Jagermech will disappear.
- [x] A2) If the Raven then turns towards the Jager (while still OFF) so that it is in sector view, the Jager will reappear.
- [x] A3) If the Raven then toggles its radar ON then OFF, the Jager will disappear.

- [x] B) If the Raven turns its radar ON and then OFF, the Jagermech will disappear.
- [x] B2) If, after B, the Enfield turns its radar ON and then OFF, the Jagermech will reappear.

**SCENARIO 2**

Wanting to dive further I altered the conditions of the test and had everyone on flat ground with no terrain variations, slopes or whathaveyou to interfere.

I then moved the units like so:

https://i.imgur.com/RVNP02B.png

In this, both the Raven and Enfield have their radars ON. The following behaviour was observed:

- [x] A) If the Raven turns its radar OFF the Jagermech will disappear/become a radar blob for the Enfield, even though it is still in sector range of the Enfield.

- [x] A2) If the Enfield then turns its radar OFF then ON, nothing changes.
- [x] A3) If EITHER the Raven OR the Enfield turn AWAY, the Jagermech will reappear.

If, before step A, EITHER mech turns to face away from the Jager, then it will NOT disappear when the Raven turns its radar off.

This seems to happen with the Raven only, possibly due to some kind of interference with ECM. Testing by replacing the Raven with a non-ECM mech did not produce the same results, but it did produce another issue:

**SCENARIO 3**

Here I used two Locusts and the Jager in a similar configuration to the first scenario.

https://imgur.com/lj2B7YW

For this scenario both Locusts have their radars on. The following behaviour was observed:

- [x] A) Moving the Locust that is looking away from the Jagermech infront of the other Locust makes the Jager disappear from view (sector is being interfered with by friendly models in the way)
- [x] B) Turning both Mechs radar OFF creates random intervals where the Jagermech becomes visible and then invisible, with nothing else moving or changing.

I'm sorry.

**SCENARIO 4**
Similar setup to before, Jagermech slightly down a slope, with a Raven and Locust like so:

https://imgur.com/r9aaF4O

Everyone starts with radar ON. The following behaviour was observed:

Step 1: Turn the Locust towards the Jagermech; the Jager becomes visible (though it is not in Radar of the Locust due to the slope) https://imgur.com/IIGkM6b
Step 2: Turn the Raven's Radar Off; the Jager becomes invisible. https://imgur.com/4lB5aVE
Step 3: Turn the Locust's radar off; the Jager becomes visible again. https://imgur.com/FDAQDPe

This happens with other Mechs besides the Locust but seems less consistent, ie I used an Enfield as well but it didn't always happen consistently.

**Comment by FLOZi** [comment]
Ideally, send me replays so I can see exactly how you are setting up these tests

**Comment by FLOZi** [comment]
2A confirmed.
2B, for me, the Jager disappears altogether if Enfield toggles to off, and is radar blob when it is on.
2C, for me the Jager remains hidden if Enfield turns away (but is still in raven sector), but is correctly reset if raven turns away and back towards i.e. it re-enters raven sector

It is almost certainly to do with special case ECM handling

**Comment by zverofaust** [comment]
Found some more issues:

Similar setup to before, Jagermech slightly down a slope, with a Raven and Locust like so:

https://imgur.com/r9aaF4O

Everyone starts with radar ON. The following behaviour was observed:

Step 1: Turn the Locust towards the Jagermech; the Jager becomes visible (though it is not in Radar of the Locust due to the slope) https://imgur.com/IIGkM6b
Step 2: Turn the Raven's Radar Off; the Jager becomes invisible. https://imgur.com/4lB5aVE
Step 3: Turn the Locust's radar off; the Jager becomes visible again. https://imgur.com/FDAQDPe

This happens with other Mechs besides the Locust but seems less consistent, ie I used an Enfield as well but it didn't always happen consistently.

**Comment by FLOZi** [comment]
1A1 and 1A2 confirmed. Suspect this is still a BAP issue but will check with another mech.

**Comment by FLOZi** [comment]
aa01fea should address everything here, but please recheck all the scenarios.

Have discovered that certain circumstances can cause 'flickering' of a unit being in and out of the raytrace check. I suggest we keep an eye out for it and if it occurs in actual gameplay then I can take steps to mitigate it (cache results looking for matching results across several frames before allowing a change in status).

**Comment by zverofaust** [comment]
Have rechecked and not noticed any similar behaviour.

**Comment by FLOZi** [comment]
Cool, closing for now. Though the 'visual stutter' does seem much more prevalent now.
