### ISSUE TITLE
Perks stackable 3 times

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#132]
Instead of Perks giving a single 15% bonus, make Perks stackable up to 3 times by 5% each (for a total of 15% for all three tiers). With a I-II-III little text in the corner to show the rank. Maybe I/III or something to make it obvious.

Perks (they dont need to have silly names, but they can)

- [x] Dead Shot (Weapon Accuracy)
- [x] Trigger Finger (Rate of Fire)
- [x] Trigger Discipline or Fire Discipline (Heat gen)
- [x] Eagle Eye (Sector sight range)
- [x] Peak Conditioning (Leg turn speed, acceleration/braking)
- [x] Parkour! (Time to initiate jump)
- [x] King of the Hill (capture speed)
- [x] Cannonball (DFA damage, see #146)
- [x] Wastelander (Increase salvage drops from kills, see #147)

**Comment by FLOZi** [comment]
5% compounded or of the original value?

1.05 x 1.05 x 1.05 = 1.157625
1 + 0.5+0.5+0.5 = 1.15

**Comment by zverofaust** [comment]
1.15

**Comment by FLOZi** [comment]
df706cfa5be6624f7c7a8f8e537df3133729c949 is a start.

Currently uses arabic numerals rather than roman, can do it if you want.
Also it is currently compounded, not of the original value, as it is (much) easier.

**Comment by zverofaust** [comment]
Checklist added. The last two require other future mechanics so are low priority.

**Comment by FLOZi** [comment]
Completed as of cd99a85
