### ISSUE TITLE
Switching team crashes gui_dropzonestatus.lua

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#133]
Start a game, use /cheat, use /team 1

[f=0000302] Cheating is enabled!
[f=0000395] [widgets.lua] Error: false
[f=0000395] [widgets.lua] Error: Error in GameFrame(): [string "LuaUI/Widgets/gui_dropzonestatus.lua"]:42: bad argument #1 to 'GetTeamRulesParam' (number expected, got nil)
[f=0000395] [widgets.lua] Error: Removed widget: Dropzone Status Debug

**Comment by FLOZi** [comment]
Known issue, to be honest the widget only exists for debugging dropzones and just restarting it (even e.g. during demo replay) will bring it back on.
