### ISSUE TITLE
A /given unit's sector LOS will not work, and radar will stop working

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#134]
- Start a singleplayer test game
- After countdown, /give a unit to team 1 somewhere
- Then /give a unit to team 0 (your team) within radar range of the first

Observation: The team 1 unit will show up on radar, but will not become visible when your Mech looks at it. Moving into 'autodetect' range will make it appear, but moving outside that range will again revert it to only a radar blob.

Part 2, after the above 3 steps:
- Move your unit outside of radar range of the Team 1 unit
- Move it back into radar range

Observation: Team 1 unit will not re-appear on radar.

Team 1 unit was in default mode, ie had its radar on, etc. Teams were NOT switched, just /give [unit] 1 to spawn it.

**Comment by FLOZi** [comment]
unitenteredradar not working if not in sector, leaving sector into radar works ok. ECM not showing up in sector only autovision. Weird stack error.

**Comment by FLOZi** [comment]
Believe this is closed after test game tonight. Reopen if not.
