### ISSUE TITLE
mcl_gui_dropship_menu and mcl_center_camera LUA broken on match start

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#136]
[f=-000001] [widgets.lua] Error: Error in Initialize(): [string "LuaUI/Widgets/mcl_gui_dropship_menu.lua"]:397: attempt to concatenate global 'mySidePrefix' (a nil value)
[f=-000001] [widgets.lua] Error: Removed widget: MC:L - Dropship Menu

and

[f=0000174] [widgets.lua] Error: Error in UnitCreated(): [string "LuaUI/Widgets/mcl_center_camera.lua"]:19: GiveOrderToUnit(): bad command ID
[f=0000174] [widgets.lua] Error: Removed widget: MC:L - Center camera

**Comment by FLOZi** [comment]
The former has been broken for ages. I had a look at fixing it and failed. Fixing the latter.
