### ISSUE TITLE
LBX seems to be firing both grapeshot and HE shell at very close range

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#137]
Tested using FS_Hollander

At very close range (see image) the LBX seems to be firing both grapeshot and HE shell. It is definitely firing the HE, and I hear the grapeshot impact sound though at these close ranges it's impossible to see.

This only occurs at extremely close range; beyond that it functions normally (HE fires at long range, grapeshot at short, until you get point blank).

![image](https://user-images.githubusercontent.com/12214376/87314581-70fcce80-c4f1-11ea-9bc1-e8525d5655be.png)

**Comment by FLOZi** [comment]
Seems like potentially engine issue: https://springrts.com/mantis/view.php?id=6407

Will try implementing the workaround there at some point, though its not really preferable as we want the 'typical' behaviour to follow the regular AC10.

**Comment by FLOZi** [comment]
Fixed in maintenance spring builds: https://github.com/spring/spring/commit/9f505631acfa709c0e84b3b74e224d632f51903a might be time to update engine.

**Comment by FLOZi** [comment]
Gonna close this one as the solution is engine based, not much for me to do about it.
