### ISSUE TITLE
Jumpjets only fire once

### ISSUE THREAD

**Issue by FLOZi** [SpringMCLegacy/SpringMCLegacy#139]
Seen with Chimera and Spider in multiplayer games; cannot replicate in spring.exe directly.

Replay 18/7/20 with kmar and Firedow on Aberdeen. Not that it helps much. Maybe to do with turn command, or interaction with turn and aiming/combat, or something is messing up lastJump variable.

**Comment by zverofaust** [comment]
I have noticed this issue too but I've also seen it reset. Happened with a Catapult that got stuck in a Mechbay; I could tell it to jump out, which it did. It got stuck again (damn low ammo!) and tried to get it to jump but wouldn't. A minute or two later I tried again and it worked.

**Comment by FLOZi** [comment]
Think it is due to the jumpjet perk and the timer/bar not working properly, as Spider was fine without the perk in 22/7 game with Player01 on DSDR
