### ISSUE TITLE
Desyncs on 104.0

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#140]
Desync 07/21 Flozi vs Zvero vs Firedow GRC

Desync message (by Firedow) occurred when orbital bombardment called by Zvero.

**Comment by FLOZi** [comment]
Desync 23/07 FFA Code_Bot, Kmar, Firedow on GRC. Nor orbital strike used.

**Comment by FLOZi** [comment]
Desync 14/7 4 FFA, FLOZi, Buumi, Firedow, zv3ro on Stronghold.

**Comment by FLOZi** [comment]
No desyncs so far on 104-1544, closing for now!
