### ISSUE TITLE
Destination/movement line/cursor disappears when MASC is active

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#148]
Normally when a unit is given a mode/patrol etc order, it will show a copy of the cursor at the destination and a line drawn between the unit and its destination. 

However when MASC is activated on a unit, it will not.

**Comment by FLOZi** [comment]
Easily fixed. Do you want a custom run cursor whilst we're at it?

**Comment by FLOZi** [comment]
Not so easily fixed, but now irrelevant with the changes to Run & MASC.
