### ISSUE TITLE
Reinforced Legs mod doesn't seem to reinforce the legs

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#150]
Tested with Victor 11D stomping a Panther to death, once with Reinforced Legs, once without.

By the time the Panther died, in both instances the legs seemed to have taken equal damage (bright red).

**Comment by FLOZi** [comment]
Fixed in bf6cca8ddf3091a8d62b8503aba45e4127c7eb81
