### ISSUE TITLE
APC Broken?

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#22]
[f=0002217] Error: LuaRules::RunCallIn: error = 2, UnitLoaded, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_dronelauncher.lua"]:120: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
[C]: in function 'pairs'
[string "LuaRules/Gadgets/unit_dronelauncher.lua"]:120: in function 'UnitLoaded'
[string "luagadgets/gadgets.lua"]:1421: in function <[string "luagadgets/gadgets.lua"]:1418>
(tail call): ?
[C]: in function 'AttachUnit'
[string "scripts/dropship_markvii.lua"]:51: in function <[string "scripts/dropship_markvii.lua"]:48>
[C]: in function 'sp_CallAsUnit'
[string "LuaRules/Gadgets/unit_script.lua"]:303: in function 'CallAsUnit'
[string "LuaRules/Gadgets/unit_beaconbuild.lua"]:168: in function '?'
[string "LuaRules/Gadgets/api_delay.lua"]:57: in function 'GameFrame'
[string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>

**Comment by FLOZi** [comment]
Not sure how this happens, possibly a result of not cleaning up tables when a APC dies. That needs addressing anyway so will test if it fixes this.

Notes on how to reproduce would be useful!
