### ISSUE TITLE
Automatic CORPSE generation

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#24]
Using pre or post or WHATEVER, create corpses automatically without needing to make a new bloody file. Whether its in unitdef, or a new gadget, whatever.

Corpse files will always have vast majority of their attributes identical. They all use "FF_Unitname_X.s3o" for their files. They have the same footprint/collision volumes as their parent unit. Their 'damage' should always be some % of the original unit (50? 25?). 'Metal' will always be a % of the original unit (10%?). 

So should be easy?

**Comment by FLOZi** [comment]
In an ideal world, we also need a way to have corpses with representative limbs missing.

**Comment by FLOZi** [comment]
Basic request was done for a long time, could follow suit of vehicles and just blow off the arms in the death script so corpses are always lacking them, but atm the corpses just use regular living model file.

**Comment by zverofaust** [comment]
Aesthetically Mechs could explode, sending body parts flying as the wreckage crumples to the ground. The effect is weird on vehicles though. But yeah we do need death anims of some kind.

**Comment by FLOZi** [comment]
Well I was just thinking the arms, not legs. Alternatively it should be possible to have all possible combinations of removed limbs accounted for, and spawn the desired one reflective of the current state of the mech, but will require separate models for each (possible to auto-gen the defs though). And I'm wary of adding to the list of art requirements!
