### ISSUE TITLE
EleMENTAL behaviour changes

### ISSUE THREAD

**Issue by FLOZi** [SpringMCLegacy/SpringMCLegacy#3]
First, please make a whole squad of Elementals come out the ship at the same time. Having one little guy riding the elevator 5 times in a row is silly. In fact I am thinking doing this for all vehicles, just have them spurt out all at once, who gives a fuck if they clip through each other its just a game. Anyway other Elemental changes: they should use their jumpjets more. As in their basic mode of transport should be jumping everywhere and almost never walking. They also need to have some sort of quasi-gunship (a la TA) attack mode where they're constantly jumping around in an “arc” around their target, rather than sitting there. Lastly, it would be cool if squads of Elementals moved together like an actual squad, they shouldn't go trekking off on their own.

**Comment by FLOZi** [comment]
Ideally elementals would just guard squad leader, but they need JJ to keep up. That or fix APC to work as intended!

**Comment by zverofaust** [comment]
Working Elementals is low priority anyway. More a cool gimmick than anything.

**Comment by FLOZi** [comment]
I still think APC + VTOL based elementals might work best

**Comment by zverofaust** [comment]
Closing because obviously BA act differently now. May re-open for debugging and polish.
