### ISSUE TITLE
maxRange & maneuverLeash based on Weapon 1 range

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#32]
'maxRange' unitdef should be equal to whatever range a unit's weapon 1 has (maybe - 50 just to be safe?). maneuverLeash should be.. idk, let's try 1.5x Weapon 1's range? 2x? Whatever, it can be worked on. 

inb4 LRM boats give no fucks and go off chasing shit on the other side of the map.

**Comment by FLOZi** [comment]
This was for vehicles so imo addressed by 57207454c5ab43fff39338804bf43c7a95db3dcd
