### ISSUE TITLE
Jumpjet ranges

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#36]
Different mechs should have different ranges for the jump jets. This should be determined by a replacement for the 'canjump' tag called 'jumpjets', with a number denoting number of jumpjets and thus range. For example, Osiris OSR-3D has 4 jumpjets while Osiris OSR-4D has 8, aka twice the range.

**Comment by FLOZi** [comment]
Resolved by efb5f22dff3f4ff71674c2d28bfb85f878f6fc58
