### ISSUE TITLE
Unitdef Overhaul: "More customparams now than Man"

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#39]
Creating unique params that fit our game to take the place of 'legacy' TA/Spring defines.

- [x] Mass & buildCostEnergy = 'tonnage' (e.g. 45), mass is 100 * tonnage;
- [x] maxVelocity = 'speed' in KPH (e.g. 90), maxVelocity is 'speed' / 20 for Mechs, / 30 for vehicles;
- [x] buildCostMetal = 'price' in C-Bills (e.g. 15000);
- [x] 'armor' table (type and tons) (e.g. armor = {type = "standard", tons = 5.5},;
- [x] maxDamage = 'tonnage' / 10 + 'armor' (tons) * 1000 (in that order); (e.g. 20 tons w/ 2 tons armor = maxDamage=4000)
- [ ] armor types for armordefs; standard, ferro, heavyferry, lightferro, stealth, vehicle;. 
- [x] 'canjump' = 'jumpjets' (number determines range, default 0/no JJ ability?);
- [x] 'torsoturnspeed' = based on speed because why not? 'speed' * 5 seems adequate.
- [ ] 'heatlimit' want to do something about this? Make it 'heatsinks'? Turn it into a table for single/double? Low priority;
- [x] change 'canmasc', 'hasbap' and 'hasecm' to simply 'masc', 'bap' and 'ecm' etc;
- [x] change maxammo to count tons and convert to appropriate number of shots as detailed in /weapons/ammo.txt

**Comment by FLOZi** [comment]
a892c8b implements most of these (no canjump or heatlimit or canmasc change) but needs testing - particularly the armor table. Also atm speed is /20 for mechs and vehicles

**Comment by zverofaust** [comment]
Closing as the vast majority of this is done and the rest are minor.
