### ISSUE TITLE
Buildpics should indicate abilities

### ISSUE THREAD

**Issue by FLOZi** [SpringMCLegacy/SpringMCLegacy#41]
& special weapons?

ECM / Jump / BAPs / AMS (NARC, TAG?)

**Comment by zverofaust** [comment]
I would like to put this information somewhere prominent on the Unit Card via symbols and show a preview of the card when mousing over Mechs in the build menu.

**Comment by FLOZi** [comment]
I don't think that rules out putting it on the BP too though.

**Comment by gajop** [comment]
I don't think this belongs to the build pic (png file), but rather should be a separate icon that could be put at arbitrary places (including over the build pic if that's wanted) and ideally even mouse-overed for details.

**Comment by gajop** [comment]
So can we close this one? It's fairly easy to just add chili images, and it's much more flexible:
- it's possible to easily modify if and where buildpics are shown
- there is no need to rebuild the buildpics (which takes time and pollutes commits) once the ability icon changes or mechs get/lose certain abilities

**Comment by FLOZi** [comment]
In any case we need additional ability icons for those not already shown by the healthbar/status widget (namely BAP, AMS, Jump)

**Comment by gajop** [comment]
You're right, I think I stole the jump icon from ZK or some such game (see firestarter here: http://i.imgur.com/72pT6JT.png).

I think it's neat if we can reuse icons in multiple places (status+map+commands+build UI). It makes it faster to grasp their meaning. Might use existing map icons (https://github.com/SpringMCLegacy/SpringMCLegacy/tree/master/icons) to show class in UI.

**Comment by FLOZi** [comment]
I'll close this in favour of tracking all ability icons in #74
