### ISSUE TITLE
TAG & NARC should increase missile accuracy / guidance

### ISSUE THREAD

**Issue by FLOZi** [SpringMCLegacy/SpringMCLegacy#45]
As title.

**Comment by zverofaust** [comment]
If we do this we should probably rethink TAG and Narc.

**Comment by zverofaust** [comment]
Why are you making this issue if accuracy/guidance can't be dynamically changed? :P

**Comment by FLOZi** [comment]
It was in either CurrentIssues.txt or Todo.rtf which I transferred to github issues

**Comment by zverofaust** [comment]
Alternatively we could make TAG'd targets simply take more damage from certain missiles.
