### ISSUE TITLE
New MaxRange Issues

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#48]
Did some investigating, here are my findings:

First off, all UnitMaxRange seems to do is control at which range a unit will give itself an attack order on an enemy unit. In other words, it's ManeuverLeashLength; it tells a unit what range a target has to be before it will give itself an attack order on it, nothing more. Units will still only attack with their longest-ranged weapons.. except, if their longest-ranged weapon isn't Weapon1, they can't, because it'll be /slaved/ to Weapon1, which isn't in range and can't shoot. The unit won't try to move into Weapon1 range; it'll still only move close enough to get /any/ weapon in range. 

And to make matters worse, MoveState seems to affect UnitMaxRange somehow. Here's a pic: http://i.imgur.com/PtEl8Hg.jpg In it, three Mithras tanks had 3 different engagement ranges based on their movestate (top=Hold Pos, mid=Maneuver, bottom=Roam). UnitMaxRange here was set at 0.8 of Weapon1 range. Hold Pos was the most 'accurate' and stopped to engage at around 80% of CERMBL range as it should've. Maneuver stopped at just about on CERMBL range. Roam stopped outside of range. Note that in every instance, the /instant/ the vehicle was given an attack order, it stopped to shoot because it found a weapon was in range. In Roam's instance its AC2 was in range, so it didn't have to move. But the AC2 can't fire because it's slaved to a CERMBL, which was out of range. All UnitMaxRange did was determine how close the Mithras' had to be to be given an attack order on the enemy tank, NOT at what range it should move to engage.

**Comment by FLOZi** [comment]
Closed by 57207454c5ab43fff39338804bf43c7a95db3dcd
