### ISSUE TITLE
Most Mechs won't enter Mechbay unless manually moved extremely close

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#50]
When told to enter a Mechbay most Mechs will walk up to within several meters of it but never enter. This seems to happen most with large and/or/slow Mechs? The player has to manually move the Mech extremely close before clicking on it to enter in order for it to work.

**Comment by FLOZi** [comment]
Still happening? This was prior to outpost pads. If so, any particular maps / points / mechs worse than others?
