### ISSUE TITLE
Dropships, either don't shoot them, or make them weaker

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#53]
ATM it's a waste of a unit's attention and ammo to shoot dropships when they should be shooting other things. Even with 4 AC20 turrets and 6 HGauss Atlas an Upgrade Dropship will survive. So either make killing them reasonably doable or make Mechs not shoot them!

**Comment by FLOZi** [comment]
Making them destructible should have major ramifications for the player that loses one (i.e. no more upgrades, plain game-over if Union is destroyed), so if we want to go down that route we need some careful balancing. 

In the short-term we can either stop them being targetted altogether, or greatly reduce their priority (change their https://springrts.com/wiki/Gamedev:UnitDefs#Tag:power and make them badtargetcategory)

**Comment by FLOZi** [comment]
190afa336a69631d7c828ad7e4f8bdd0966753ce makes priority very low, should be sufficient for now. Destructibility is a long term topic for another day.
