### ISSUE TITLE
Perks

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#58]
EDIT: After discussions about what type of perks are and aren't possible, here is a more thorough list of Perks.

- [x] Heatsink Efficiency (Capacity AND Dissipation)
- [x] MASC Efficiency (Duration, Reload AND/OR Heat)
- [x] Jump Jet Efficiency (Range AND Reload)
- [x] AMS Range
- [x] Sensor Range
- [x] Narc Beacon Duration (drop default to 30-45s, Perk increases to 60s imho)
- [ ] *Insulated Electronics (Reduce PPC effect duration)
- [x] Federated Suns: Autocannon Range (NOT LBX)
- [x] Draconis Combine: PPC & MRM Range
- [x] Lyran Alliance: Gauss Range
- [x] Free Worlds League: LRM Range
- [x] Capellan Confederation: ECM Range (& Strength when applicable)

*I think this would be cool.

Note that a few Perks are merged here, I think this is necessary given there are 7 non-faction-specific Perks here.

**Comment by FLOZi** [comment]
Don't really like centralised perks - they are a reward for keeping your pilots alive. Don't even like it as a supplement as I think that will become confusing if we have two perking systems.

**Comment by zverofaust** [comment]
We could easily parcel the centralized perk system as some sort of technology/research tree, where increases to various stats or abilities comes via getting better technology.

It is more a way to deal with inundation of Perks if we plan to do more.

**Comment by zverofaust** [comment]
Updated this based on discussion.

**Comment by FLOZi** [comment]
MASC efficiency is now only limited by heat generated

**Comment by FLOZi** [comment]
Note that although "here are 7 non-faction-specific Perks here." most mechs have relatively few as AMS, Jump, MASC are ability-specific. Not sure about the insulation, maybe only for ECM mechs?

**Comment by zverofaust** [comment]
ECM and BAP which are affected by PPC strikes. 

I didn't realize this would leave us with a single perk for a lot of "simple" Mechs. But maybe this is fine.

**Comment by FLOZi** [comment]
All mechs have at least 2 (Sensors + Heat).

**Comment by zverofaust** [comment]
Do they need more?
