### ISSUE TITLE
SSRMs sometimes don't shoot.

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#59]
**SNIP** Turns out, some of what I was seeing was due to Radar being Off on Mechs transfered to other teams. Some if it, however, was not. It appears that when a unit is transfered to another team, it's ECM 'remains' on its original team. So when I transfered the Stiletto to Team 1 its ECM still behaved as if it were on Team 0 and so jammed any enemy Mechs that the Stiletto got close to, as the game believed those enemies were being covered by a friendly ECM. Likewise, Team 0 Mechs saw Team 1 Stiletto's ECM as its own and so ignored it and were able to fire jammable weapons.

HOWEVER, I should note that the LOS system seems to see the ECM normally as Team 1 Stiletto WON'T be detected by Radar, only direct LOS. Weapons however do not and will ignore the ECM as friendly if the Mech is spotted.

I have no idea if this even relates to the problems we've been having with your SSRMs in MP games.

**Comment by FLOZi** [comment]
I'm convinced this was due to me forgetting about radar targeting. Closing for now.
