### ISSUE TITLE
Balance Clans to be more 'offensive' and IS to be more 'defensive'

### ISSUE THREAD

**Issue by FLOZi** [SpringMCLegacy/SpringMCLegacy#6]
Clans have the faster and more powerful Mechs; we should retool each side to play off this, with IS getting more robust support (Beacon Upgrades etc) while Clans get less. For example, Clans get the very temporary “orbital turret drops” and no Bunker/limited prefab garrison upgrade, while IS would get beefier dedicated casemate weapons and Bunker upgrade options. To help differentiate the sides and offer different gameplay opportunities outside of the purely aesthetic and lore-based “hurfblurf dirty freebornz”.

**Comment by zverofaust** [comment]
This doesn't really need to be an 'issue' just something to keep in mind.
