### ISSUE TITLE
RAC Nerf - Jamming

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#63]
RAC are supposed to be not as ridiculously amazing as ours, mainly because we're missing two important drawbacks - exponential jamming chance and heat increase.

The heat part is easy, we can just increase their heat. The jamming part.. is hard to communicate to players, but I think we can in two ways. First, if it jams, make it play an audible sound, something that sounds like an AC shot and metal slamming against metal. You know, those kinds of sounds that instantly make you think "oh fuck, something just broke". The second is turning the weapon red in the Unit Card, or even better, having it flash between red and green for the duration it's jammed. A third option would be to emit smoke from the end of the barrel.

I think a combination of a horrible breaking sound, flashing weapon slot and smoke should be enough to clue players into why their RAC stopped firing.

I'd like to do this because there are lots of Mechs with RACs that I'm passing up because RACs are fucking ridiculous now. And they should be ridiculous, but they should also come with the chance of disastrous consequences at random. It's a very random weapon with very random results, that's kind of its "thing".

**Comment by FLOZi** [comment]
Nerfed via other means for now.
