### ISSUE TITLE
Unit Voice Responses

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#66]
Not only are these cool to have, they can also help us deal with some aspects of communicating things to players. Having a unit _say_ they are Narcing or TAGing something, or say they can't lock onto things because of jamming, or saying an enemy Mech is spotted when it comes into view, will help.

Also we should try to get in touch wit hte guy who's GF did our current voices, so she can do more!

**Comment by FLOZi** [comment]
Essentially addressed by 67556ca6f457f7830f3b563cef2c2b9c241f5368, though BB is still missing several sounds these days.
