### ISSUE TITLE
URGENT: Radar Off 

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#67]
Either remove this function or make BAP spot them.

**Comment by FLOZi** [comment]
I still think it has merit so I'd rather not remove it altogether. BAP-detection is probably possible though the implementation isn't great (requires polling all untis within a radius of each BAP-mech every few frames). Another possibility is that radar-off doesn't affect visibility but does affect locking? Or just reverts to Spring default 'radar blobs' with innaccuracy (dislike this the most)

**Comment by zverofaust** [comment]
Affecting locking opens up a whole host of issues of not really being able to communicate this to players. With ECM, at least, it's ECM stopping it, and we can show that there's ECM. With radar off it doesn't make any sense.

**Comment by FLOZi** [comment]
BAP spot then?

**Comment by zverofaust** [comment]
Yeah should be okay.
