### ISSUE TITLE
Key Binds

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#68]
Several special functions require keybinds. Some already have them, some don't. Let's make a list.

- [x] C = Coolant Flush

- [x] V = MASC

- [x] G = Guard/Defend

- [x] R = Radar On/Off

- [ ] Q = BAP Pulse (plsssss)

- [ ] E = ECM Burst, if we do it

- [x] J = Jumpjets (broken atm)

- [x] T = Turn (broken atm)

I realized Attack and Stop kind of make WASD camera controls a PITA so fuck'em.

**Comment by FLOZi** [comment]
At the moment Turn is bound to R, because T is 'camera track'.

**Comment by zverofaust** [comment]
Pretty much done, we can look at ECM Burst and BAP Pulse active abilities later.
