### ISSUE TITLE
Enlarged Mech interactive area

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#70]
Currently it's basically impossible to click on enemies if they're moving because the 'activation' area around Mechs is absurdly tiny. I realize this also has to do with hitvolumes in some way, but if it's possible, I'd like to increase dramatically this area so that actually having your Mechs target who you want is viable in a close-range Light mech brawl.

**Comment by FLOZi** [comment]
Is based on the per-piece colvols, so not possible currently
