### ISSUE TITLE
Limitations on moving Dropzone

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#71]
This is an incredibly abuse-prone tactic, allowing you to instantly teleport a massive battlestation anywhere on the map at a moment's notice. We need a way to limit it.

Options include simply removing the ability (it will still move automatically to the nearest flag if your home base is taken), giving it a delay/resetting your dropship timer (30 seconds), and/or making it cost money. I prefer one of the first two or a combination of the last two.

**Comment by zverofaust** [comment]
Still feel the same way. Is it imperitive people are able to move their dropzones? I also had a thought of making Dropzones immune to capture until/unless the player has no other beacons. Tbh I don't see "chopping off the head" as viable or wanted mechanic/design nor does it make sense that a dropship wouldnt want to land somewhere. They're supposed to be mobile bases in and of themselves.

**Comment by FLOZi** [comment]
I'm confused as your first question seems at odds with your later statement. Yes they need to be able to move their dropzones as they're supposed to be mobile bases? Are you proposing landing a dropship anywhere? Doesn't that radically exacerbate the problem here?
