### ISSUE TITLE
Mechs sometimes get stuck after using Turn

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#72]
When a Mech is standing still and given a Turn command, often it will become stuck after turning to face its new direction, looping the turning anim and unable to move ever again. The looping animation happened before, but prior to the "Turn/JJ fix" recently, telling the Mech to move would jar it out of its animation and it'd go back to normal. Now though it simply becomes stuck and will never move or turn or anything again.

**Comment by FLOZi** [comment]
'often'

And yes, this is why I didn't want to do it the way I did it previously. I will take a look.
