### ISSUE TITLE
Unit Bars & Status Effects

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#74]
The number of Bars units have is ridiculous. We really need to reign this in, and ensure that only the most vital information is communicated with "stuff" around a Unit, and in the most clear and understandable way. To this end I have pushed a number of status effects icons in /bitmaps/icons/ for us to render over units. We'll need to have some way for these to stack in rows and/or columns, and stack dynamically, like this: http://i.imgur.com/2PLOsCM.png Some of these status effects counter or supersede others, so I doubt it will be possible for a Mech to have more than 8 of these at any one time (two rows of 4).

So to that end I propose the following:
- [ ] Add a LIGHT BLUE section to the HP bar that corresponds with how much of the HP is determined by armour. It can take up the end of the current HP bar like this: http://i.imgur.com/hwTdU3W.png or a thinner bar added ontop of it like this http://i.imgur.com/o0XSoxI.png
- [x] Remove Coolant Bar, this is not vital information.
- [x] Remove MASC Bar, this is not vital information (and we shouldn't have a MASC bar!)
- [x] Remove XP Bar and replace with XP icon when a unit has a Perk available. This could/should even be off to the side and not a part of other status effects (owning player only).
- [x] Remove Ammo Bars and replace with single NoAmmo icon that will show if ANY weapon has no ammo. The player can then investigate further via the unit card. This could possibly be placed somewhere off to the side rather than with the other icons as it's not a status effect per se... (owning Player only)
- [x] Remove Narc, TAG & PPC rings/text and replace with applicable icons (all players)
- [x] Add "MissileLock" icon whenever a unit is shot at by a lock-on missile (LRM, ATM, SSRM or Arrow) (either owning only or all)
- [ ] Add "ECM" to any Mech whose radar has been turned off by proximity to enemy ECM, or manually turned off by the player (owning player only).
- [x] Add "ECMProtection" to any friendly Mechs within range of a friendly, active ECM field (owning player only)
- [x] Add "ECMProtectionEnemy" to any enemy Mechs in range of their own active ECM field (enemy players only)
- [x] Add "NoLock" icon to any Mech attempting to fire lock-on missiles at a target protected by ECM (owning player)
- [ ] Add "ECCM" to any unit that has its ECM nullified by an enemy ECM in proximity (owning player only)

**Comment by FLOZi** [comment]
Potentially need icons for BAP, AMS, and Jump in addition, whether displayed on unitcard or buildpic tooltip etc.
