### ISSUE TITLE
Repair & Resupply Tweaks

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#75]
I have a couple of propositions I feel would benefit the game.
- [x] Mobile Mechbays should repair at a slightly slower rate. Currently an Atlas can go from near-death to perfect health in 3 seconds or so. 
- [x] A way to prevent cheeseplay where Mechs will quickly repair in the midst of a fight, like during the Code_Man game when I popped my near-dead Hunchback into the Mechbay in center just before he died. Slowing repair rate might help but there should be some mechanic in place preventing repairs when a Mech is under attack. I don't think it should also apply to if the Mechbay is being attacked; proliferation of LRMs etc. 
- [ ] Mechs inside the Dropzone beacon area when a Dropship is landed should re-arm, and possibly repair too. Maybe just to like 50% or 75% (for both main HP and limbs), but won't replace destroyed limbs.

**Comment by FLOZi** [comment]
I'm really not a fan of part 3; it detracts from the importance of the mechbay - which has just had 2 major nerfs from the other parts of this.

**Comment by zverofaust** [comment]
I would still like Mechbays to provide a function to swap Omnimech configurations as a reason for making Omnimechs in the first place. With three upgrade points per beacon now I don't think we need Dropships to repair/rearm - there's plenty of room for mechbays.

**Comment by FLOZi** [comment]
I'll close this one for now then. Omni mechs feels like a new issue.
