### ISSUE TITLE
"Link Lost" Mechs aren't re-absorbed when free space/weight becomes available

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#77]
if you use a C3 to build more Mechs, then lose the C3 causing Mechs to become Link Lost, they won't be re-absorbed into your command when space becomes available (aka through the death of your pre-existing lance).

**Comment by FLOZi** [comment]
What do we want to happen if there is a lance slot but insufficient tonnage?
