### ISSUE TITLE
Custom 'range circle' display/replacement as multi-hexagon grid

### ISSUE THREAD

**Issue by FLOZi** [SpringMCLegacy/SpringMCLegacy#8]
Simple circles are so out of style; need a cooler looking way to display ranges, something like this: http://imgur.com/wCNDnAR EXTRA BONUS if this is done 'procedurally' so I don't have to make a seperate image for every possibly range of every possible ranged weapon or ability.
This type of design could replace everything from unit footprints, beacon capture area, etc, rather than the large, single hexagon or crudely rendered circles.

**Comment by gajop** [comment]
So something like http://imgur.com/ttjRuZq to begin with, but maybe with filled circles?
I think at the very least outer edges need to be much sharper so players know what the range of the object is.
It doesn't need to affect LOS does it?
