### ISSUE TITLE
C3 destruction/selling handling

### ISSUE THREAD

**Issue by gajop** [SpringMCLegacy/SpringMCLegacy#82]
There are a number of issues with C3s being destroyed while the mechs are still "using it":
1. Ordering mechs in a dropship and then selling all C3s before it arrives will not disable any new mechs
2. It's possible to buy a number of C3s, order 4 atlases and sell all C3s without any mechs going offline: you basically get free tonnage this way (it seems only lances are considered when offlining mechs, and not tonnage). If you decide to build new C3s, the atlases won't take the appropriate tonnage (you get free tonnage this way)
3. There are some issues that make you not lose any tonnage when selling/buying C3s when over limit, but this might be related to 2.
I also suggest you avoid using "energy" with its storage component to represent tonnage, it seems hacky and your code reflects it - that's just my opinion though.

**Comment by FLOZi** [comment]
From hell's heart I stab at thee

**Comment by gajop** [comment]
Still not fixed:
- build 2 atlases
- build 1 C3
- order 1 more atlas
- sell c3
- all 3 atlases available at 150/200 tonnage

**Comment by FLOZi** [comment]
Default Tonnage limit shouldn't allow 2 Atlases to start with, are you building them with dropship or /give?

**Comment by gajop** [comment]
I order them. When launching from WebLobby to set the initial C-Bills to 100000 I also get 200 as initial tonnage (despite leaving it as a default 150).

**Comment by FLOZi** [comment]
Couple of possible solutions:

1. Make lances respect the tonnage limit, i.e. each lance can only contain 150 tonnes. This would mean with default settings you could only ever have 3 assaults, one in each lance. Restricts the players ability to reassign lances and any tactical choices stemming form that e.g. having a recce lance, assault lance, support lance. May be over thinking it as generally speaking C3s are expensive enough that this kind of play isn't possible anyway.

2. Automatically reassign mechs out of still-active lances if they exceed tonnage when you lose a C3, either to preserve numbers or preserve best mech (as is done when a mech will fit in a lower lance). This opens up all kind of possible issues with mechs swapping around by themselves.

3. Have no automatic reassign, but check for any mechs that exceed tonnage and Link Lost them. Allow the player to move mechs between lances when they are link lost in order to regroup. i.e. Player can manually select which mechs are currently 'active', but cannot violate tonnage.

I prefer 3, sticks closest to the original conception, but would need some clever UI to do properly I suspect. Also not the easiest to implement in order to fix this particular issue (That would be #1)

**Comment by gajop** [comment]
I'd go for option 4 as well, but that's because I think the whole lance concept is a bit outdated.
Despite the battletech definitions of 4/5(clans?) mechs per group, in RTS games it was mostly used as an easy and automatic way of putting mechs in control groups. In most games you could override that to your arbitrary groupings.

I think it's perfectly fine to limit mechs by both tonnage and slot number, but there's no need to work with a strict 4-slot as lance system.

**Comment by FLOZi** [comment]
Currently players can violate that by using ctrl groups but there are UI reasons for it. It's also a way to hard-restrict the number of mechs (Zvero even favours restricting to just a __single__ lance!)

**Comment by FLOZi** [comment]
18:55:58] <gajop> when C3 goes off just offline random mechs if tonnage/slots aren't met
[18:56:15] <gajop> but i don't think you need to satisfy tonnage per lance
[18:56:18] <gajop> thus #4
[18:56:34] <[S44]FLOZi> only #1 requires tonnage per lance
[18:56:48] <[S44]FLOZi> #4 says 'dgaf about tonnage except when purchasing'
[18:57:11] <[S44]FLOZi> i.e. allow '380 out of 200 tons used'
[18:57:39] <gajop> ah, then no xD
[18:58:04] <gajop> i really don't want "buy C3, buy mechs, sell C3" to become a common tactic
[18:58:36] <gajop> and it would, as it's a massive bonus in power (you can then order a mech bay for example)


So I would think gajop you would prefer #2? Automatic reassign with tonnage conserved.

**Comment by gajop** [comment]
Yep, although I wouldn't do any automatic sorting, just fill empty slots if available.

**Comment by FLOZi** [comment]
But filling empty slots implies sorting if you want to respect tonnage!

**Comment by gajop** [comment]
Nah, just offline the last mechs until you have satisfied the limits.
Example:
Initial:
Slot 1 Mech: 40t
Slot 2 Mech: 40t
Slot 3 Mech: 40t
Slot 4 Mech: 60t
Slot 5 Mech: 60t
Total tonnage: 240
Available tonnage: 150 + 150 from C3 (not sure of the exact number C3 gives, but not important)

C3 dies:
Available tonnage: 150, Total: 240
Offline mech in slot 5 -> Total tonnage: 180. Offline mech in slot 5, total tonnage: 120.
Is this ideal? No, but it's simple and users can plan for this (by reordering mechs or by manually offlining/onlining mechs).

**Comment by FLOZi** [comment]
So you want LIFO queue + manual option. I think this is what hokomoko was leaning towards too

**Comment by ashdnazg** [comment]
manually offline-online mechs is just a cumbersome selection.

**Comment by gajop** [comment]
@FLOZi Yep! This is obviously not optimal, but it's a very simple, deterministic system and players can arrange their mech slot order for it.
An alternative would be to do a 2-pass, first by offlining all mechs until limit is satisfied and then, in reverse order, onlining mechs that still satisfy the limit restrictions.
This would disable everything but the Atlas and Slot 3/4 mechs.

**Comment by FLOZi** [comment]
Was resolved to go with option 4 (tonnage is a purchasing constraint, slots a control constraint), then considered splitting tonnage increase and slots increase into separate structures, or even tonnage as a dropship upgrade perk (again the above). I think I now favour this approach; it makes slots fragile but tonnage increase permanent.

**Comment by FLOZi** [comment]
Due to b32ef406b2463c4c6380cd0da49202922a1658bd et al I'm going to re-label this as feedback

**Comment by FLOZi** [comment]
The Dropship-gives-tonnage, C3-gives-slots mechanism appears to be working fine.
