### ISSUE TITLE
BA won't re-enter APC if APC under attack.

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#85]
Had an APC unload some BA on some fools and kill it. As they were coming back, APC was attacked by something from outside its range (it never fired). Only one BA got in, the rest hovered around it indefinitely.

**Comment by FLOZi** [comment]
Looks to be more general and not just limited to when APC is under attack, sometimes it works sometimes it doesn't. Probably a wait-for-Spring-101 and lua based transports.
