### ISSUE TITLE
Some error messages during a spectator game

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#94]
- [x] First, watched an AI build a C3 Array, and it was destroyed a second or two after it deployed and caused this error:

[f=0019895] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_beaconbuild.lua"]:169: bad argument #2 to 'EditUnitCmdDesc' (number expected, got nil)
stack traceback:
	[C]: in function 'EditUnitCmdDesc'
	[string "LuaRules/Gadgets/unit_beaconbuild.lua"]:169: in function 'ToggleUpgradeOptions'
	[string "LuaRules/Gadgets/game_flagmanager.lua"]:286: in function 'FlagCapChange'
	[string "LuaRules/Gadgets/game_flagmanager.lua"]:354: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>
	(tail call): ?

- [x] Second, this happened several times: 

[f=0022434] Error: LuaRules::RunCallIn: error = 2, UnitDestroyed, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/ai_spambot.lua"]:343: bad argument #1 to 'tonumber' (value expected)
stack traceback:
	[C]: in function 'tonumber'
	[string "LuaRules/Gadgets/ai_spambot.lua"]:343: in function 'UnitDestroyed'
	[string "luagadgets/gadgets.lua"]:1276: in function <[string "luagadgets/gadgets.lua"]:1273>
	(tail call): ?

- [x] Then, this bigass error log spewed out when one of the teams' tickets ran to 0 (it was a 4-player FFA so the game didn't end)

[f=0031591] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_vehiclepad.lua"]:210: attempt to index field '?' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:210: in function '?'
	[string "LuaRules/Gadgets/api_delay.lua"]:57: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>
	(tail call): ?
[f=0031728] Error: LuaRules::RunCallIn: error = 2, UnitUnloaded, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_vehiclepad.lua"]:185: attempt to index field '?' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:185: in function 'Wander'
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:239: in function 'UnitUnloaded'
	[string "luagadgets/gadgets.lua"]:1440: in function <[string "luagadgets/gadgets.lua"]:1437>
	(tail call): ?
	[C]: in function 'co_resume'
	[string "LuaRules/Gadgets/unit_script.lua"]:256: in function 'WakeUp'
	[string "LuaRules/Gadgets/unit_script.lua"]:277: in function <[string "LuaRules/Gadgets/unit_script.lua"]:265>
	(tail call): ?
	[string "LuaRules/Gadgets/unit_script.lua"]:772: in function <[string "LuaRules/Gadgets/unit_script.lua"]:770>
[f=0031729] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_vehiclepad.lua"]:210: attempt to index field '?' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:210: in function '?'
	[string "LuaRules/Gadgets/api_delay.lua"]:57: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>
	(tail call): ?

This also broke ALL vehicle pads left in the game.

**Comment by FLOZi** [comment]
More lua errors:

- [ ] unit_purchasing
[f=0020748] Error: LuaRules::RunCallIn: error = 2, UnitDestroyed, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_purchasing.lua"]:171: attempt to compare nil with number
stack traceback:
	[string "LuaRules/Gadgets/unit_purchasing.lua"]:171: in function 'TeamAvailableGroup'
	[string "LuaRules/Gadgets/unit_purchasing.lua"]:272: in function 'LanceControl'
	[string "LuaRules/Gadgets/unit_purchasing.lua"]:640: in function 'UnitDestroyed'
	[string "luagadgets/gadgets.lua"]:1276: in function <[string "luagadgets/gadgets.lua"]:1273>
	(tail call): ?

- [ ] unit_vehiclePad
[f=0037129] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_vehiclepad.lua"]:211: attempt to index field '?' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:211: in function '?'
	[string "LuaRules/Gadgets/api_delay.lua"]:57: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>
	(tail call): ?

- [ ] unit_vehiclePad
[f=0038688] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_vehiclepad.lua"]:104: attempt to index field '?' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:104: in function 'RandomVehicle'
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:135: in function '?'
	[string "LuaRules/Gadgets/api_delay.lua"]:57: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>
	(tail call): ?

**Comment by zverofaust** [comment]
Another, happened when one of the AI players in a 4-AI FFA got to 0 tickets:

[f=0041301] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_vehiclepad.lua"]:212: attempt to index field '?' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:212: in function '?'
	[string "LuaRules/Gadgets/api_delay.lua"]:57: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>
	(tail call): ?
[f=0041459] Error: LuaRules::RunCallIn: error = 2, GameFrame, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_vehiclepad.lua"]:212: attempt to index field '?' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:212: in function '?'
	[string "LuaRules/Gadgets/api_delay.lua"]:57: in function 'GameFrame'
	[string "luagadgets/gadgets.lua"]:838: in function <[string "luagadgets/gadgets.lua"]:836>
	(tail call): ?
