### ISSUE TITLE
LA_HunterUpgrade might be breaking Vpads?

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#95]
I've noticed very frequently while watching AI games that Lyran vpads will become clogged with Hunter upgrades. Well, what seems to be happening is that the Vpad never unloads the Hunter and it is stuck inside it. Any attempt to select the Hunter will also select the Vehicle Pad. This stops the Vpad from ever working again. Quizzically this *only* happens with the Hunter Upgrade, no other unit.

**Comment by FLOZi** [comment]
Is this still the case?
