### ISSUE TITLE
AI Tweaks/Enhancements/Fixes/Improvements

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#96]
Some suggestions for fixing/improving AI:

1) Remove jumping. This causes problems primarily with Mechs jumping into deep ravines or getting stuck on the side of mountains and being unable to make their next jump because of the terrain. On maps with lots of cliffs and such (TMA-0 is biggest offender) most Mechs can get stuck.

2) Increase time AI spends idling at beacon/attack points. This seems to be really random; sometimes AI Mechs will sit on beacons for like 2 minutes after capturing it, other times they'll never stop and immediately go on to the next beacon. 

3) AI should focus on beacons closer to its startpos first. More often than not they'll end up heading off to a faraway beacon.

4) Bit of behavioural AI: Make them maneuver by giving them move orders to random points around a target, or something, while shooting. Or just make them move randomly (move randomdistancebetween25-100, random direction from current position). I don't know how movement orders are handled like this; is it mapped based? IE, can you get the current xy map coords of the unit, and then give it a random order between like -100 to +100 on x and y so it basically can end up anywhere within a 200 square of its current position? Do this every few seconds/when the unit is idle/unmoving while attacking.

5) Runaway: If Mech gets below 25% health make it runaway. Either to a Mechbay to repair (if possible with AI) or to homebase, which will repair/re-arm them.

6) Same goes for if the Mech runs out of ammo. RTB and get more.

7) Homebase should repair and replenish ammo for AI mechs if they can't use Mechbays. Maybe have it based on the Dropship. I'd actually like for this to be an ability for Players, too, because Mechbays are a PITA. At the very least for ammo.

**Comment by FLOZi** [comment]
Potentially for 3 (& 1):
Instead of taking naieve approach of beacons directly as-the-crow-flies closest to starting dropzone, use the pathfinder API (Path:GetPathWayPoints) to iterate over waypoints to find walking distances. For jump mechs, iterate over this list of waypoints from both ends looking for 2 points within jump distance of each other.

Potentially for 4:
If a jump mech is within weapon range of an enemy, but not able to target (Spring.GetUnitWeaponHaveFreeLineOfFire or Spring.GetUnitWeaponTestTarget et al) attempt to jumpsnipe, if mech fires, repeat.

**Comment by zverofaust** [comment]
Most of the problem with AI using jumpjets is they will often get themselves into position where they can't jump to their target despite being in range. Usually this is when they get themselves wedged up onto a cliff side and their jump target is on the other side of the cliff. The Jump gadget will disallow a jump and the unit will sit there indefinitely. So we'll need AI to cancel their jump command after x seconds of not being able to jump and try walking instead, or something.

**Comment by zverofaust** [comment]
Also the fact that the current way JJ mechs are given orders (dozens of them stretched out in a line to intended destination) results in movement orders in the middle of lakes, ontop of impassable mountains etc.

**Comment by FLOZi** [comment]
Most of these are beyond SpamBot so I made a new label for possible SmartBot behaviours
