### ISSUE TITLE
Spring.exe crash

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#98]
Seemed to be just when a Urbanmech was about to jump.

Stacktrace:

[f=0022687] Error: Spring 100.0 has crashed.
[f=0022687] Error: DLL information:
[f=0022687] Error: 0x00400000	spring
[f=0022687] Error: 0x76ed0000	ntdll
[f=0022687] Error: 0x75980000	kernel32
[f=0022687] Error: 0x76a80000	KERNELBASE
[f=0022687] Error: 0x768f0000	ADVAPI32
[f=0022687] Error: 0x74cc0000	msvcrt
[f=0022687] Error: 0x74ff0000	sechost
[f=0022687] Error: 0x74aa0000	RPCRT4
[f=0022687] Error: 0x74a40000	SspiCli
[f=0022687] Error: 0x74a30000	CRYPTBASE
[f=0022687] Error: 0x701f0000	GLU32
[f=0022687] Error: 0x6ce70000	OPENGL32
[f=0022687] Error: 0x75740000	GDI32
[f=0022687] Error: 0x757f0000	USER32
[f=0022687] Error: 0x74d70000	LPK
[f=0022687] Error: 0x74d80000	USP10
[f=0022687] Error: 0x70f40000	DDRAW
[f=0022687] Error: 0x719a0000	DCIMAN32
[f=0022687] Error: 0x755a0000	SETUPAPI
[f=0022687] Error: 0x74fc0000	CFGMGR32
[f=0022687] Error: 0x758f0000	OLEAUT32
[f=0022687] Error: 0x75440000	ole32
[f=0022687] Error: 0x757d0000	DEVOBJ
[f=0022687] Error: 0x736d0000	dwmapi
[f=0022687] Error: 0x74c90000	IMAGEHLP
[f=0022687] Error: 0x75b50000	SHELL32
[f=0022687] Error: 0x74ba0000	SHLWAPI
[f=0022687] Error: 0x736f0000	WINMM
[f=0022687] Error: 0x753a0000	WS2_32
[f=0022687] Error: 0x74b90000	NSI
[f=0022687] Error: 0x10000000	DevIL
[f=0022687] Error: 0x70c00000	MSVCP80
[f=0022687] Error: 0x70c90000	MSVCR80
[f=0022687] Error: 0x6b600000	OpenAL32
[f=0022687] Error: 0x00330000	libgcc_s_sjlj-1
[f=0022687] Error: 0x70780000	vorbisfile
[f=0022687] Error: 0x68140000	ogg
[f=0022687] Error: 0x64cc0000	vorbis
[f=0022687] Error: 0x62e80000	zlib1
[f=0022687] Error: 0x70e40000	libfreetype-6
[f=0022687] Error: 0x64f80000	libfontconfig-1
[f=0022687] Error: 0x68f40000	libexpat-1
[f=0022687] Error: 0x62aa0000	glew32
[f=0022687] Error: 0x6c740000	SDL2
[f=0022687] Error: 0x753e0000	IMM32
[f=0022687] Error: 0x75a80000	MSCTF
[f=0022687] Error: 0x734a0000	VERSION
[f=0022687] Error: 0x73490000	profapi
[f=0022687] Error: 0x74940000	uxtheme
[f=0022687] Error: 0x6b720000	atiglpxx
[f=0022687] Error: 0x58fd0000	atioglxx
[f=0022687] Error: 0x60130000	atiadlxy
[f=0022687] Error: 0x737b0000	PROPSYS
[f=0022687] Error: 0x72d70000	USERENV
[f=0022687] Error: 0x72d90000	WTSAPI32
[f=0022687] Error: 0x76ea0000	PSAPI
[f=0022687] Error: 0x71b20000	IPHLPAPI
[f=0022687] Error: 0x736c0000	WINNSI
[f=0022687] Error: 0x74c50000	WINTRUST
[f=0022687] Error: 0x74e20000	CRYPT32
[f=0022687] Error: 0x767a0000	MSASN1
[f=0022687] Error: 0x6b5b0000	atigktxx
[f=0022687] Error: 0x75110000	CLBCatQ
[f=0022687] Error: 0x72d60000	shfolder
[f=0022687] Error: 0x6ca30000	MMDevApi
[f=0022687] Error: 0x6c3f0000	dsound
[f=0022687] Error: 0x6c3c0000	POWRPROF
[f=0022687] Error: 0x6ca70000	AUDIOSES
[f=0022687] Error: 0x6b860000	dinput8
[f=0022687] Error: 0x6c480000	HID
[f=0022687] Error: 0x05b00000	XInput1_3
[f=0022687] Error: 0x730e0000	mswsock
[f=0022687] Error: 0x70a40000	wship6
[f=0022687] Error: 0x72e50000	sslsp105
[f=0022687] Error: 0x72e30000	wshtcpip
[f=0022687] Error: 0x69330000	dbghelp
[f=0022687] Error: Exception: Access violation (0xc0000005)
[f=0022687] Error: Exception Address: 0x74cd43f9
[f=0022687] Error: Stacktrace for Spring 100.0:
[f=0022687] Error: (0) C:\Windows\syswow64\msvcrt.dll(strlen+0x26) [0x74CD43F9]
[f=0022687] Error: (1) Unknown [0x20A27E28]
[f=0022687] Error: (2) D:\Spring\spring.exe [0x00573285]
[f=0022687] Error: (3) D:\Spring\spring.exe(skirmishAiCallback_Cheats_setEnabled+0x69100) [0x008148C0]
[f=0022687] Error: (4) D:\Spring\spring.exe(skirmishAiCallback_Cheats_setEnabled+0x6aca9) [0x00816469]
[f=0022687] Error: (5) D:\Spring\spring.exe(skirmishAiCallback_Cheats_setEnabled+0x6c4e9) [0x00817CA9]
[f=0022687] Error: (6) D:\Spring\spring.exe(skirmishAiCallback_Cheats_setEnabled+0x6889e) [0x0081405E]
[f=0022687] Error: (7) D:\Spring\spring.exe(skirmishAiCallback_Cheats_setEnabled+0x693c0) [0x00814B80]
[f=0022687] Error: [ErrorMessageBox][1] msg="Spring has crashed:
  Access violation.

A stacktrace has been written to:
  D:\Spring\infolog.txt" IsMainThread()=1 fromMain=0
[f=0022687] Error: [ErrorMessageBox][2]
[f=0022687] [SpringApp::ShutDown][1]
[f=0022687] [ThreadPool::SetThreadCount][1] #wanted=0 #current=3 #max=4
[f=0022687] [ThreadPool::SetThreadCount][2] #threads=0
[f=0022687] [SpringApp::ShutDown][2]
[f=0022687] [KillLua][1]
[f=0022687] [KillLua][2]
[f=0022687] [KillLua][3]
[f=0022687] Reloaded cmdcolors from file: cmdcolors.tmp
[f=0022687] [KillLua][4]
[f=0022687] [~CGame]1]
[f=0022687] [KillLua][1]
[f=0022687] [KillLua][2]
[f=0022687] [KillLua][3]
[f=0022687] [KillLua][4]
[f=0022687] [KillMisc][1]
[f=0022687] [KillMisc][2]
[f=0022687] [KillRendering][1]
[f=0022687] [KillInterface][1]
[f=0022687] [KillInterface][2]
[f=0022687] [KillSimulation][1]
[f=0022687] [KillSimulation][2]
[f=0022687] [CCollisionHandler] dis-/continuous tests: 0/4322340
[f=0022687] [KillSimulation][3]
[f=0022687] [KillSimulation][4]
[f=0022687] [~CPathCache(32x32)] cacheHits=0 hitPercentage=0% numHashColls=0 maxCacheSize=0
[f=0022687] [~CPathCache(32x32)] cacheHits=401 hitPercentage=35% numHashColls=0 maxCacheSize=23
[f=0022687] [~CPathCache(128x128)] cacheHits=0 hitPercentage=0% numHashColls=0 maxCacheSize=0
[f=0022687] [~CPathCache(128x128)] cacheHits=43683 hitPercentage=25% numHashColls=0 maxCacheSize=201
[f=0022687] Statistics for RectangleOptimizer: 0%
[f=0022687] Statistics for RectangleOptimizer: 0%
[f=0022687] [KillSimulation][5]
[f=0022687] [~CGame][2]
[f=0022687] [~CGame][3]
[f=0022687] [SpringApp::ShutDown][3]
[f=0022687] Statistics for local connection:
Received: 37738 bytes
Sent: 238309 bytes

[f=0022687] Writing demo: D:\Spring\demos\20160124_203807_Stronghold_beta_100.sdf
[f=0022687] [SpringApp::ShutDown][4]
[f=0022687] [SpringApp::ShutDown][5]
[f=0022687] [SpringApp::ShutDown][6]
[f=0022687] [SpringApp::ShutDown][7]
[LuaSocket] Dumping luasocket rules:
[LuaSocket] TCP_CONNECT ALLOW * -1
[LuaSocket] TCP_LISTEN  ALLOW * -1
[LuaSocket] UDP_LISTEN  ALLOW * -1
[SpringApp::ShutDown][8]
[WatchDog::Uninstall][1] hangDetectorThread=013FAD40
[WatchDog::Uninstall][2]
[WatchDog::Uninstall][3]
[SpringApp::ShutDown][9]
Error: [ErrorMessageBox][3]
Error: [ErrorMessageBox][4]
Fatal: Spring: Unhandled exception
Spring has crashed:
  Access violation.

A stacktrace has been written to:
  D:\Spring\infolog.txt

**Comment by FLOZi** [comment]
[20:34:42] <[S44]FLOZi> stacktrace here is junk right? https://github.com/SpringMCLegacy/SpringMCLegacy/issues/98
[20:36:09] <abma_irc> hmm, its weird but not junk: http://paste.springfiles.com/view/e400083e
[20:38:08] <abma_irc> looks more like translation fails: version isn't detected correctly for some reason
[20:38:11] ** [bling]nix left the channel (Quit: IRC connection timeout).
[20:41:22] <abma_irc> hmm, ok garbage it seems :-|
[20:41:31] <abma_irc> sorry, you're right
[20:42:08] <abma_irc> replay + complete infolog.txt would be useful

**Comment by FLOZi** [comment]
No replay -> closing

**Comment by zverofaust** [comment]
Happened again, when a Mech in mid-jump (and mid-air) was killed by PPCs.

Infolog: http://pastebin.com/XS2uqdFU

Replay: https://www.dropbox.com/s/7p8yvl7ou3u2mzk/20160127_230401_Stronghold_beta_100.sdf?dl=0

**Comment by FLOZi** [comment]
https://springrts.com/mantis/view.php?id=5048

**Comment by FLOZi** [comment]
Closing for now, reopen if it happens on 101+
