### ISSUE TITLE
vehicle_unitpad.lua crash

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#99]
It appeared to happen when a team went to 0 tickets:

[f=0082852] Error: LuaRules::RunCallIn: error = 2, UnitUnloaded, [Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_vehiclepad.lua"]:194: attempt to index field '?' (a nil value)
stack traceback:
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:194: in function 'Wander'
	[string "LuaRules/Gadgets/unit_vehiclepad.lua"]:250: in function 'UnitUnloaded'
	[string "luagadgets/gadgets.lua"]:1440: in function <[string "luagadgets/gadgets.lua"]:1437>
	(tail call): ?
	[C]: in function 'co_resume'
	[string "LuaRules/Gadgets/unit_script.lua"]:256: in function 'WakeUp'
	[string "LuaRules/Gadgets/unit_script.lua"]:277: in function <[string "LuaRules/Gadgets/unit_script.lua"]:265>
	(tail call): ?
	[string "LuaRules/Gadgets/unit_script.lua"]:772: in function <[string "LuaRules/Gadgets/unit_script.lua"]:770>

**Comment by FLOZi** [comment]
Seems to be fixed well enough by 2918e63
